// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using src.Data;

#nullable disable

namespace metvagas.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260616015841_Job")]
    partial class Job
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("src.Modules.Entities.Company", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp")
                        .HasColumnName("created_at")
                        .HasComment("Data de criacao");

                    b.Property<string>("LogoUrl")
                        .HasColumnType("varchar(500)")
                        .HasColumnName("logo_url")
                        .HasComment("URL do logo da empresa");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("name")
                        .HasComment("Nome da empresa");

                    b.Property<string>("NormalizedName")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("normalized_name")
                        .HasComment("Nome normalizado para buscas");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp")
                        .HasColumnName("updated_at")
                        .HasComment("Data de atualizacao");

                    b.Property<string>("Website")
                        .IsRequired()
                        .HasColumnType("varchar(500)")
                        .HasColumnName("website")
                        .HasComment("Site da empresa");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("ix_companies_normalized_name");

                    b.HasIndex("Website")
                        .IsUnique()
                        .HasDatabaseName("ix_companies_website");

                    b.ToTable("companies", (string)null);
                });

            modelBuilder.Entity("src.Modules.Entities.Job", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("City")
                        .HasColumnType("varchar(100)")
                        .HasColumnName("city")
                        .HasComment("Cidade da vaga");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid");

                    b.Property<string>("ContractType")
                        .HasColumnType("varchar(20)")
                        .HasColumnName("contract_type")
                        .HasComment("Tipo de contrato: clt, pj, freelance, internship");

                    b.Property<string>("Country")
                        .HasColumnType("varchar(100)")
                        .HasColumnName("country")
                        .HasComment("Pais da vaga");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp")
                        .HasColumnName("created_at")
                        .HasComment("Data de criacao");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description")
                        .HasComment("Descricao da vaga");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("active")
                        .HasComment("Indica se a vaga ainda esta ativa");

                    b.Property<string>("OriginalUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("original_url")
                        .HasComment("URL original da vaga");

                    b.Property<DateTime>("PublishedAt")
                        .HasColumnType("timestamp")
                        .HasColumnName("published_at")
                        .HasComment("Data de publicacao da vaga");

                    b.Property<decimal>("SalaryMax")
                        .HasColumnType("numeric")
                        .HasColumnName("salary_max")
                        .HasComment("Salario maximo");

                    b.Property<decimal>("SalaryMin")
                        .HasColumnType("numeric")
                        .HasColumnName("salary_min")
                        .HasComment("Salario minimo");

                    b.Property<DateTime>("ScrapedAt")
                        .HasColumnType("timestamp")
                        .HasColumnName("scraped_at")
                        .HasComment("Data de coleta da vaga");

                    b.Property<string>("Seniority")
                        .HasColumnType("varchar(20)")
                        .HasColumnName("seniority")
                        .HasComment("Nivel de senioridade: junior, mid, senior, lead");

                    b.Property<string>("Source")
                        .HasColumnType("varchar(100)")
                        .HasColumnName("source")
                        .HasComment("Fonte de onde a vaga foi coletada");

                    b.Property<string>("State")
                        .HasColumnType("varchar(100)")
                        .HasColumnName("state")
                        .HasComment("Estado da vaga");

                    b.PrimitiveCollection<string[]>("TechStack")
                        .HasColumnType("text[]")
                        .HasColumnName("tech_stack")
                        .HasComment("Tecnologias exigidas pela vaga");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("title")
                        .HasComment("Titulo da vaga");

                    b.Property<string>("WorkMode")
                        .HasColumnType("varchar(20)")
                        .HasColumnName("work_mode")
                        .HasComment("Modalidade de trabalho: remote, hybrid, onsite");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("OriginalUrl")
                        .IsUnique()
                        .HasDatabaseName("ix_jobs_original_url");

                    b.ToTable("jobs", (string)null);
                });

            modelBuilder.Entity("src.Modules.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp")
                        .HasColumnName("created_at")
                        .HasComment("Data de criacao");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("email")
                        .HasComment("Email do usuario");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("name")
                        .HasComment("Nome do usuario");

                    b.Property<string>("PreferredCity")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("preferred_city")
                        .HasComment("Cidade de preferencia do usuario");

                    b.Property<string>("PreferredCountry")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("preferred_country")
                        .HasComment("Pais de preferencia do usuario");

                    b.Property<string>("PreferredState")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("preferred_state")
                        .HasComment("Estado de preferencia do usuario");

                    b.Property<string>("PreferredWorkMode")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("preferred_work_mode")
                        .HasComment("Modelo de trabalho escolhido pelo usuario");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp")
                        .HasColumnName("updated_at")
                        .HasComment("Data de atualizacao");

                    b.HasKey("Id");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("src.Modules.Entities.Job", b =>
                {
                    b.HasOne("src.Modules.Entities.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Company");
                });
#pragma warning restore 612, 618
        }
    }
}
