// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using src.Data;

#nullable disable

namespace metvagas.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260611025410_Company")]
    partial class Company
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("src.Modules.Entities.Company", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp")
                        .HasColumnName("created_at")
                        .HasComment("Data de criacao");

                    b.Property<string>("LogoUrl")
                        .HasColumnType("varchar(500)")
                        .HasColumnName("logo_url")
                        .HasComment("URL do logo da empresa");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("name")
                        .HasComment("Nome da empresa");

                    b.Property<string>("NormalizedName")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("normalized_name")
                        .HasComment("Nome normalizado para buscas");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp")
                        .HasColumnName("updated_at")
                        .HasComment("Data de atualizacao");

                    b.Property<string>("Website")
                        .IsRequired()
                        .HasColumnType("varchar(500)")
                        .HasColumnName("website")
                        .HasComment("Site da empresa");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("ix_companies_normalized_name");

                    b.HasIndex("Website")
                        .IsUnique()
                        .HasDatabaseName("ix_companies_website");

                    b.ToTable("companies", (string)null);
                });

            modelBuilder.Entity("src.Modules.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp")
                        .HasColumnName("created_at")
                        .HasComment("Data de criacao");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("email")
                        .HasComment("Email do usuario");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("name")
                        .HasComment("Nome do usuario");

                    b.Property<string>("PreferredCity")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("preferred_city")
                        .HasComment("Cidade de preferencia do usuario");

                    b.Property<string>("PreferredCountry")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("preferred_country")
                        .HasComment("Pais de preferencia do usuario");

                    b.Property<string>("PreferredState")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("preferred_state")
                        .HasComment("Estado de preferencia do usuario");

                    b.Property<string>("PreferredWorkMode")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("preferred_work_mode")
                        .HasComment("Modelo de trabalho escolhido pelo usuario");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp")
                        .HasColumnName("updated_at")
                        .HasComment("Data de atualizacao");

                    b.HasKey("Id");

                    b.ToTable("users", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
