// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using src.Data;

#nullable disable

namespace metvagas.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260711213300_Enhancement-v1")]
    partial class Enhancementv1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("src.Modules.Entities.Application", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp")
                        .HasColumnName("created_at")
                        .HasComment("Data de criacao");

                    b.Property<Guid>("JobId")
                        .HasColumnType("uuid")
                        .HasColumnName("job_id");

                    b.Property<string>("Notes")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("notes")
                        .HasComment("Notas da aplicação");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("varchar(20)")
                        .HasColumnName("status")
                        .HasComment("Status da aplicação");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp")
                        .HasColumnName("updated_at")
                        .HasComment("Data de atualizacao");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("JobId");

                    b.HasIndex("UserId", "JobId")
                        .IsUnique()
                        .HasDatabaseName("ix_applications_user_job");

                    b.ToTable("applications", (string)null);
                });

            modelBuilder.Entity("src.Modules.Entities.Company", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp")
                        .HasColumnName("created_at")
                        .HasComment("Data de criacao");

                    b.Property<string>("LogoUrl")
                        .HasColumnType("varchar(500)")
                        .HasColumnName("logo_url")
                        .HasComment("URL do logo da empresa");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("name")
                        .HasComment("Nome da empresa");

                    b.Property<string>("NormalizedName")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("normalized_name")
                        .HasComment("Nome normalizado para buscas");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp")
                        .HasColumnName("updated_at")
                        .HasComment("Data de atualizacao");

                    b.Property<string>("Website")
                        .IsRequired()
                        .HasColumnType("varchar(500)")
                        .HasColumnName("website")
                        .HasComment("Site da empresa");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("ix_companies_normalized_name");

                    b.HasIndex("Website")
                        .IsUnique()
                        .HasDatabaseName("ix_companies_website");

                    b.ToTable("companies", (string)null);
                });

            modelBuilder.Entity("src.Modules.Entities.FavoriteJob", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("JobId")
                        .HasColumnType("uuid")
                        .HasColumnName("job_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp")
                        .HasColumnName("created_at")
                        .HasComment("Data de criacao");

                    b.HasKey("UserId", "JobId");

                    b.HasIndex("JobId");

                    b.HasIndex("UserId", "JobId")
                        .IsUnique()
                        .HasDatabaseName("ix_favorite_jobs_user_job");

                    b.ToTable("favorite_jobs", (string)null);
                });

            modelBuilder.Entity("src.Modules.Entities.Job", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("City")
                        .HasColumnType("varchar(100)")
                        .HasColumnName("city")
                        .HasComment("Cidade da vaga");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid");

                    b.Property<string>("ContractType")
                        .HasColumnType("varchar(20)")
                        .HasColumnName("contract_type")
                        .HasComment("Tipo de contrato: clt, pj, freelance, internship");

                    b.Property<string>("Country")
                        .HasColumnType("varchar(100)")
                        .HasColumnName("country")
                        .HasComment("Pais da vaga");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp")
                        .HasColumnName("created_at")
                        .HasComment("Data de criacao");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description")
                        .HasComment("Descricao da vaga");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("active")
                        .HasComment("Indica se a vaga ainda esta ativa");

                    b.Property<string>("OriginalUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("original_url")
                        .HasComment("URL original da vaga");

                    b.Property<DateTime>("PublishedAt")
                        .HasColumnType("timestamp")
                        .HasColumnName("published_at")
                        .HasComment("Data de publicacao da vaga");

                    b.Property<decimal>("SalaryMax")
                        .HasColumnType("numeric")
                        .HasColumnName("salary_max")
                        .HasComment("Salario maximo");

                    b.Property<decimal>("SalaryMin")
                        .HasColumnType("numeric")
                        .HasColumnName("salary_min")
                        .HasComment("Salario minimo");

                    b.Property<string>("Seniority")
                        .HasColumnType("varchar(20)")
                        .HasColumnName("seniority")
                        .HasComment("Nivel de senioridade: junior, mid, senior, lead");

                    b.Property<string>("State")
                        .HasColumnType("varchar(100)")
                        .HasColumnName("state")
                        .HasComment("Estado da vaga");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("title")
                        .HasComment("Titulo da vaga");

                    b.Property<string>("WebsiteName")
                        .HasColumnType("varchar(100)")
                        .HasColumnName("website_name")
                        .HasComment("Fonte de onde a vaga foi coletada");

                    b.Property<string>("WorkMode")
                        .HasColumnType("varchar(20)")
                        .HasColumnName("work_mode")
                        .HasComment("Modalidade de trabalho: remote, hybrid, onsite");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("OriginalUrl")
                        .IsUnique()
                        .HasDatabaseName("ix_jobs_original_url");

                    b.ToTable("jobs", (string)null);
                });

            modelBuilder.Entity("src.Modules.Entities.JobMatch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AnalyzedAt")
                        .HasColumnType("timestamp")
                        .HasColumnName("analyzed_at")
                        .HasComment("Data da última análise do match");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp")
                        .HasColumnName("created_at")
                        .HasComment("Data de criacao");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("timestamp")
                        .HasColumnName("expires_at")
                        .HasComment("Data de expiração do match");

                    b.Property<bool>("IsViewed")
                        .HasColumnType("boolean")
                        .HasColumnName("is_viewed")
                        .HasComment("Indica se o usuário visualizou a recomendação");

                    b.Property<Guid>("JobId")
                        .HasColumnType("uuid")
                        .HasColumnName("job_id");

                    b.Property<decimal>("MatchScore")
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("match_score")
                        .HasComment("Score de compatibilidade");

                    b.Property<string>("ScoreBreakdown")
                        .HasColumnType("text")
                        .HasColumnName("score_breakdown")
                        .HasComment("Detalhamento do score");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("JobId");

                    b.HasIndex("MatchScore")
                        .HasDatabaseName("ix_job_matches_score");

                    b.HasIndex("UserId", "JobId")
                        .IsUnique()
                        .HasDatabaseName("ix_job_matches_user_job");

                    b.ToTable("job_matches", (string)null);
                });

            modelBuilder.Entity("src.Modules.Entities.JobSkill", b =>
                {
                    b.Property<Guid>("JobId")
                        .HasColumnType("uuid")
                        .HasColumnName("job_id");

                    b.Property<Guid>("SkillId")
                        .HasColumnType("uuid")
                        .HasColumnName("skill_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp")
                        .HasColumnName("created_at")
                        .HasComment("Data de criacao");

                    b.HasKey("JobId", "SkillId");

                    b.HasIndex("SkillId");

                    b.ToTable("job_skills", (string)null);
                });

            modelBuilder.Entity("src.Modules.Entities.SearchHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp")
                        .HasColumnName("created_at")
                        .HasComment("Data de criacao");

                    b.Property<string>("Filters")
                        .HasColumnType("varchar(500)")
                        .HasColumnName("filters")
                        .HasComment("Filtro da pesquisa");

                    b.Property<string>("SearchTerm")
                        .IsRequired()
                        .HasColumnType("varchar(500)")
                        .HasColumnName("search_term")
                        .HasComment("Pesquisa principal");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_search_histories_user_id");

                    b.ToTable("search_histories", (string)null);
                });

            modelBuilder.Entity("src.Modules.Entities.Skill", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("category")
                        .HasComment("Categoria da competencia");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp")
                        .HasColumnName("created_at")
                        .HasComment("Data de criacao");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("name")
                        .HasComment("Nome da competencia");

                    b.Property<string>("NormalizedName")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("normalized_name")
                        .HasComment("Nome normalizado para buscas");

                    b.HasKey("Id");

                    b.ToTable("skills", (string)null);
                });

            modelBuilder.Entity("src.Modules.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp")
                        .HasColumnName("created_at")
                        .HasComment("Data de criacao");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("email")
                        .HasComment("Email do usuario");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("name")
                        .HasComment("Nome do usuario");

                    b.Property<string>("PreferredCity")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("preferred_city")
                        .HasComment("Cidade de preferencia do usuario");

                    b.Property<string>("PreferredCountry")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("preferred_country")
                        .HasComment("Pais de preferencia do usuario");

                    b.Property<string>("PreferredState")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("preferred_state")
                        .HasComment("Estado de preferencia do usuario");

                    b.Property<string>("PreferredWorkMode")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("preferred_work_mode")
                        .HasComment("Modelo de trabalho escolhido pelo usuario");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp")
                        .HasColumnName("updated_at")
                        .HasComment("Data de atualizacao");

                    b.HasKey("Id");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("src.Modules.Entities.UserSkill", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("SkillId")
                        .HasColumnType("uuid")
                        .HasColumnName("skill_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp")
                        .HasColumnName("created_at")
                        .HasComment("Data de criacao");

                    b.Property<string>("Level")
                        .HasColumnType("varchar(50)")
                        .HasColumnName("level")
                        .HasComment("Nivel da competencia do usuario");

                    b.HasKey("UserId", "SkillId");

                    b.HasIndex("SkillId");

                    b.ToTable("user_skills", (string)null);
                });

            modelBuilder.Entity("src.Modules.Entities.Application", b =>
                {
                    b.HasOne("src.Modules.Entities.Job", "Job")
                        .WithMany()
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("src.Modules.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Job");

                    b.Navigation("User");
                });

            modelBuilder.Entity("src.Modules.Entities.FavoriteJob", b =>
                {
                    b.HasOne("src.Modules.Entities.Job", "Job")
                        .WithMany()
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("src.Modules.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Job");

                    b.Navigation("User");
                });

            modelBuilder.Entity("src.Modules.Entities.Job", b =>
                {
                    b.HasOne("src.Modules.Entities.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("src.Modules.Entities.JobMatch", b =>
                {
                    b.HasOne("src.Modules.Entities.Job", "Job")
                        .WithMany()
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("src.Modules.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Job");

                    b.Navigation("User");
                });

            modelBuilder.Entity("src.Modules.Entities.JobSkill", b =>
                {
                    b.HasOne("src.Modules.Entities.Job", "Job")
                        .WithMany("JobSkills")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("src.Modules.Entities.Skill", "Skill")
                        .WithMany()
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Job");

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("src.Modules.Entities.SearchHistory", b =>
                {
                    b.HasOne("src.Modules.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("src.Modules.Entities.UserSkill", b =>
                {
                    b.HasOne("src.Modules.Entities.Skill", "Skill")
                        .WithMany()
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("src.Modules.Entities.User", "User")
                        .WithMany("UserSkills")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Skill");

                    b.Navigation("User");
                });

            modelBuilder.Entity("src.Modules.Entities.Job", b =>
                {
                    b.Navigation("JobSkills");
                });

            modelBuilder.Entity("src.Modules.Entities.User", b =>
                {
                    b.Navigation("UserSkills");
                });
#pragma warning restore 612, 618
        }
    }
}
